# Generated by Django 2.2.28 on 2025-06-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smmapdfs', '0003_auto_20191126_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfsandwichemail',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('cs', 'Czech'), ('sk', 'Slovak'), ('dsnkcs', 'Škola')], max_length=80, verbose_name='Language'),
        ),
    ]
